#!/bin/bash
#kasutaja loomine failist 
echo "Kasutajate loomine kasutades faili kasutaja_nimed"
#fail, kust nimed võetakse tuleb veidike modifitseerida (algab tühja reaga, siis nimi, uuest tühi rida, siis uuest nimi
while read -r line; do ./kasutaja_lisamine.sh; done < kasutaja_nimed

#teine lahendus
#for rida in ($cat $failinimi)
#	do
#		echo $rida
#	done
