#!/bin/bash
#kasutaja loomine failist parooliga

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 kasutajad_paroolid"
else
	failinimi=$1
	if [ -f $failinimi -a -r $failinimi ]; then
		echo "fail on korras"
		for rida in $(cat $failinimi)
		do
			kasutajanimi=$(echo "$rida" | cut -f1 -d:)
			sh kasutaja_lisamine.sh $kasutajanimi
			echo "$rida" | chpasswd 
		done
	else 
		echo "probleem failiga $failinimi"
	fi
fi
